import { createHash } from "crypto";

type ReadinessSnapshot = {
  readinessScore?: number | null;
  level?: string | null;
} | null;

type ProofManifestInput = {
  id: string;
  type: string;
  title: string;
  description?: string | null;
  source?: string | null;
  sourceId?: string | null;
  xpValue: number;
  issuedAt: Date;
  user: {
    id?: string;
    username: string;
    displayName: string;
    city?: string | null;
    readinessProfile?: ReadinessSnapshot;
  };
  readinessProfile?: ReadinessSnapshot;
};

export type FilecoinArchiveManifest = {
  version: "karyra-proof-manifest-v0.1";
  archiveType: "proof-record";
  generatedAt: string;
  provider: "filecoin-demo";
  status: "simulated";
  proof: {
    id: string;
    type: string;
    title: string;
    description: string | null;
    source: string | null;
    sourceId: string | null;
    xpValue: number;
    issuedAt: string;
  };
  learner: {
    id: string | null;
    username: string;
    displayName: string;
    city: string | null;
  };
  readiness: {
    score: number;
    level: string;
  };
  checksum: {
    algorithm: "sha256";
    digest: string;
    note: string;
  };
  nextIntegration: {
    target: "Filecoin/IPFS";
    expectedFlow: string[];
  };
};

export function getJsonObject(value: unknown): Record<string, unknown> {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value as Record<string, unknown>;
  }

  return {};
}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }

  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item)).join(",")}]`;
  }

  const objectValue = value as Record<string, unknown>;
  const keys = Object.keys(objectValue).sort();

  return `{${keys
    .map((key) => `${JSON.stringify(key)}:${stableStringify(objectValue[key])}`)
    .join(",")}}`;
}

export function createSha256Digest(value: unknown) {
  return createHash("sha256").update(stableStringify(value)).digest("hex");
}

export function generateDemoFilecoinCid(proofId: string, digest?: string) {
  const compactId = proofId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 18);
  const compactDigest = digest?.slice(0, 14) ?? "manifestdemo";

  return `bafy-demo-karyra-${compactId}-${compactDigest}`;
}

export function buildProofArchiveManifest(
  proof: ProofManifestInput,
): FilecoinArchiveManifest {
  const readiness = proof.readinessProfile ?? proof.user.readinessProfile;

  const unsignedManifest = {
    version: "karyra-proof-manifest-v0.1",
    archiveType: "proof-record",
    provider: "filecoin-demo",
    status: "simulated",
    proof: {
      id: proof.id,
      type: proof.type,
      title: proof.title,
      description: proof.description ?? null,
      source: proof.source ?? null,
      sourceId: proof.sourceId ?? null,
      xpValue: proof.xpValue,
      issuedAt: proof.issuedAt.toISOString(),
    },
    learner: {
      id: proof.user.id ?? null,
      username: proof.user.username,
      displayName: proof.user.displayName,
      city: proof.user.city ?? null,
    },
    readiness: {
      score: readiness?.readinessScore ?? 0,
      level: readiness?.level ?? "BEGINNER",
    },
  };

  const digest = createSha256Digest(unsignedManifest);

  return {
    ...unsignedManifest,
    generatedAt: new Date().toISOString(),
    checksum: {
      algorithm: "sha256",
      digest,
      note: "Demo manifest checksum. In production, this digest can be used before uploading the manifest to IPFS/Filecoin.",
    },
    nextIntegration: {
      target: "Filecoin/IPFS",
      expectedFlow: [
        "Generate proof manifest",
        "Upload manifest JSON to IPFS/Filecoin storage layer",
        "Store returned CID in proof record",
        "Expose CID on public proof verification page",
      ],
    },
  };
}

export function buildArchivedProofMetadata(input: {
  existingMetadata: unknown;
  manifest: FilecoinArchiveManifest;
  cid: string;
}) {
  return {
    ...getJsonObject(input.existingMetadata),
    archive: {
      provider: "filecoin-demo",
      status: "simulated",
      cid: input.cid,
      manifestVersion: input.manifest.version,
      manifestDigest: input.manifest.checksum.digest,
      archivedAt: input.manifest.generatedAt,
      note: "Demo CID generated by Karyra MVP. Replace with real Filecoin/IPFS flow later.",
    },
    archiveManifest: input.manifest,
  };
}

export function getArchiveManifestFromMetadata(
  metadata: unknown,
): FilecoinArchiveManifest | null {
  const metadataObject = getJsonObject(metadata);
  const manifest = metadataObject.archiveManifest;

  if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) {
    return null;
  }

  const manifestObject = manifest as Partial<FilecoinArchiveManifest>;

  if (manifestObject.version !== "karyra-proof-manifest-v0.1") {
    return null;
  }

  return manifestObject as FilecoinArchiveManifest;
}
