import Link from "next/link";
import { notFound } from "next/navigation";
import { SubmitButton } from "../../../components/submit-button";
import { completeLessonAction, startLessonAction } from "../../actions/learner";
import { formatLearningStatus, getLearningStatusTone, getLessonLearningState } from "@/lib/learning";

type PageProps = { params: Promise<{ slug: string }> };
type ContentBlock = { type: string; text?: string };
type LessonContent = { blocks?: ContentBlock[] };
type QuizOption = { id: string; text: string };

export default async function LessonDetailPage({ params }: PageProps) {
  const { slug } = await params;
  const state = await getLessonLearningState(slug);
  if (!state) notFound();
  const { lesson, courseLessons, previousLesson, nextLesson, currentIndex, progress, courseProgress, courseQuests } = state;
  const content = lesson.content as LessonContent;
  const blocks = content.blocks ?? [];
  const completionRedirect = nextLesson ? `/lessons/${nextLesson.slug}` : `/courses/${lesson.module.course.slug}`;

  return (
    <main className="min-h-screen bg-slate-950 text-white"><section className="mx-auto grid w-full max-w-7xl gap-6 px-4 py-6 pb-24 md:px-8 md:py-12 lg:grid-cols-[0.72fr_0.28fr]">
      <article className="min-w-0"><Link href={`/courses/${lesson.module.course.slug}`} className="text-sm font-bold text-emerald-300">← {lesson.module.course.title}</Link>
        <header className="mt-5 rounded-[2rem] border border-white/10 bg-white/[0.04] p-5 md:p-7"><p className="text-xs font-black uppercase tracking-[0.22em] text-emerald-300">Lesson {currentIndex + 1} of {courseLessons.length}</p><h1 className="mt-3 text-3xl font-black tracking-tight md:text-5xl">{lesson.title}</h1><div className="mt-4 flex flex-wrap gap-2 text-xs font-black"><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-emerald-300">{lesson.type}</span><span className="rounded-full bg-white/10 px-3 py-1 text-slate-300">{lesson.estimatedMinutes} min</span><span className="rounded-full bg-white/10 px-3 py-1 text-slate-300">{lesson.xpReward} XP</span><span className={`rounded-full border px-3 py-1 ${getLearningStatusTone(progress?.status ?? "NOT_STARTED")}`}>{formatLearningStatus(progress?.status ?? "NOT_STARTED")}</span></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><form action={startLessonAction}><input type="hidden" name="lessonSlug" value={lesson.slug} /><SubmitButton variant="secondary" pendingText="Starting...">Start / Resume</SubmitButton></form><form action={completeLessonAction}><input type="hidden" name="lessonSlug" value={lesson.slug} /><input type="hidden" name="redirectTo" value={completionRedirect} /><SubmitButton pendingText="Completing...">{nextLesson ? "Complete & Next Lesson" : "Complete Lesson"}</SubmitButton></form></div></header>
        <div className="mt-8 rounded-[2rem] border border-white/10 bg-white/[0.035] p-5 md:p-7">{blocks.length === 0 ? <p className="leading-8 text-slate-300">This lesson does not have content blocks yet.</p> : <div className="space-y-5">{blocks.map((block, index) => block.type === "heading" ? <h2 key={`${block.type}-${index}`} className="text-2xl font-black text-white">{block.text}</h2> : <p key={`${block.type}-${index}`} className="text-base leading-8 text-slate-300">{block.text}</p>)}</div>}</div>
        {lesson.questions.length > 0 ? <section className="mt-6 rounded-[2rem] border border-sky-400/20 bg-sky-400/10 p-5 md:p-6"><p className="text-xs font-black uppercase tracking-wide text-sky-300">Knowledge Check</p><h2 className="mt-2 text-2xl font-black">Quiz singkat</h2><p className="mt-2 text-sm leading-6 text-slate-300">Untuk MVP, quiz ini masih preview/read-only. Fokus utama saat ini adalah reading flow dan lesson completion.</p><div className="mt-5 grid gap-4">{lesson.questions.map((question) => { const options = question.options as QuizOption[]; return <div key={question.id} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Question {question.order} · {question.points} point</p><h3 className="mt-2 font-black text-white">{question.prompt}</h3><div className="mt-4 grid gap-2">{options.map((option) => <div key={option.id} className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm leading-6 text-slate-300"><strong>{option.id.toUpperCase()}.</strong> {option.text}</div>)}</div></div>; })}</div></section> : null}
        <nav className="mt-6 grid gap-3 md:grid-cols-2">{previousLesson ? <Link href={`/lessons/${previousLesson.slug}`} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 transition hover:border-emerald-400/40"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Previous</p><h3 className="mt-1 font-black">{previousLesson.title}</h3></Link> : <Link href={`/courses/${lesson.module.course.slug}`} className="rounded-2xl border border-white/10 bg-white/[0.04] p-4 transition hover:border-emerald-400/40"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Course</p><h3 className="mt-1 font-black">Back to syllabus</h3></Link>}{nextLesson ? <Link href={`/lessons/${nextLesson.slug}`} className="rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-4 transition hover:bg-emerald-400/15"><p className="text-xs font-black uppercase tracking-wide text-emerald-300">Next lesson</p><h3 className="mt-1 font-black">{nextLesson.title}</h3></Link> : <Link href={`/courses/${lesson.module.course.slug}`} className="rounded-2xl border border-emerald-400/25 bg-emerald-400/10 p-4 transition hover:bg-emerald-400/15"><p className="text-xs font-black uppercase tracking-wide text-emerald-300">Course complete</p><h3 className="mt-1 font-black">Back to course summary</h3></Link>}</nav>
        {courseQuests.length > 0 ? <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[0.035] p-5 md:p-6"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Optional after learning</p><h2 className="mt-2 text-2xl font-black">Practice challenges</h2><p className="mt-2 text-sm leading-6 text-slate-400">Quest tersedia sebagai latihan tambahan setelah lesson. Ini bukan jalur utama, tetapi bisa membantu membangun readiness.</p><Link href="/quests" className="mt-4 inline-flex text-sm font-black text-emerald-300">Open optional quests →</Link></section> : null}
      </article>
      <aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-[2rem] border border-white/10 bg-white/[0.04] p-5"><p className="text-xs font-black uppercase tracking-wide text-emerald-300">Course Roadmap</p><h2 className="mt-2 text-xl font-black">{lesson.module.course.title}</h2><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${courseProgress.progressPct}%` }} /></div><p className="mt-2 text-xs text-slate-500">{courseProgress.completedLessons}/{courseProgress.totalLessons} lessons complete</p><div className="mt-5 grid gap-2">{courseLessons.map((courseLesson, index) => { const isCurrent = courseLesson.id === lesson.id; return <Link key={courseLesson.id} href={`/lessons/${courseLesson.slug}`} className={`rounded-2xl border p-3 text-sm transition ${isCurrent ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-100" : "border-white/10 bg-slate-950/50 text-slate-300 hover:border-emerald-400/30"}`}><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{String(index + 1).padStart(2, "0")} · Module {courseLesson.moduleOrder}</p><p className="mt-1 font-bold">{courseLesson.title}</p></Link>; })}</div></div></aside>
    </section></main>
  );
}
