import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

function generateDemoFilecoinCid(proofId: string) {
  const compactId = proofId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 24);
  return `bafy-demo-karyra-${compactId}`;
}

export async function POST(request: NextRequest) {
  try {
    const body = (await request.json()) as {
      proofId?: string;
    };

    if (!body.proofId) {
      return NextResponse.json(
        {
          ok: false,
          message: "proofId is required.",
        },
        { status: 400 },
      );
    }

    const proof = await prisma.proofRecord.findUnique({
      where: {
        id: body.proofId,
      },
    });

    if (!proof) {
      return NextResponse.json(
        {
          ok: false,
          message: "Proof record not found.",
        },
        { status: 404 },
      );
    }

    if (proof.archivedToFilecoin && proof.filecoinCid) {
      return NextResponse.json({
        ok: true,
        message: "Proof record already archived.",
        proof,
      });
    }

    const filecoinCid = generateDemoFilecoinCid(proof.id);

    const updatedProof = await prisma.proofRecord.update({
      where: {
        id: proof.id,
      },
      data: {
        archivedToFilecoin: true,
        filecoinCid,
        metadata: {
          ...(typeof proof.metadata === "object" &&
          proof.metadata !== null &&
          !Array.isArray(proof.metadata)
            ? proof.metadata
            : {}),
          archive: {
            provider: "filecoin-demo",
            status: "simulated",
            cid: filecoinCid,
            archivedAt: new Date().toISOString(),
            note: "Demo CID generated by Karyra MVP. Replace with real Filecoin/IPFS flow later.",
          },
        },
      },
    });

    return NextResponse.json({
      ok: true,
      message: "Proof record archived to Filecoin demo layer.",
      proof: updatedProof,
    });
  } catch (error) {
    console.error("[POST /api/proofs/archive]", error);

    return NextResponse.json(
      {
        ok: false,
        message: "Failed to archive proof record.",
      },
      { status: 500 },
    );
  }
}